-- Run this once in the Supabase SQL Editor.
-- Materials/receipts are logged as individual entries through the week (not one overwritable
-- total), so a plumber can add a receipt each time they hit the store and the week's total
-- accumulates. Used by the "My pay" take-home estimate via api/paycheck.js.
--
-- If you already ran an earlier version of this file, it created a `weekly_pay_entries`
-- table with a single overwritable total per week - this replaces it with a log table.
-- Safe to run either way.

drop table if exists weekly_pay_entries;

create table if not exists materials_entries (
  id bigint generated by default as identity primary key,
  plumber_id text not null,
  week_start date not null,
  amount numeric not null,
  created_at timestamptz not null default now()
);

create index if not exists materials_entries_plumber_week_idx
  on materials_entries (plumber_id, week_start);

-- Same lockdown pattern as plumbers: no anon/authenticated access at all, only the
-- service role (used by api/paycheck.js) can read or write. This is each plumber's
-- own expense data - other plumbers should not be able to see it either.
do $$
declare
  pol record;
begin
  for pol in select policyname from pg_policies where schemaname = 'public' and tablename = 'materials_entries'
  loop
    execute format('drop policy if exists %I on public.materials_entries', pol.policyname);
  end loop;
end $$;

alter table materials_entries enable row level security;
